# Generated by Django 4.0 on 2022-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(unique=True)),
                ('step', models.IntegerField(default=0)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_gift', models.CharField(max_length=100)),
                ('tel_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
