# Generated by Django 4.0 on 2022-01-16 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('tel_number', models.CharField(max_length=100)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(unique=True)),
                ('step', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimCardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.simuser')),
                ('sim_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.simcardoption')),
                ('user_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.gift')),
            ],
        ),
        migrations.DeleteModel(
            name='BotUsers',
        ),
        migrations.AddField(
            model_name='botuser',
            name='sim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.simcardoption'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.gift'),
        ),
    ]
