# Generated by Django 4.0 on 2022-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_botuser_gift_simcardoption_simuser_userorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
