# Generated by Django 4.0 on 2022-01-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userorder_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='tel_number',
            field=models.CharField(default=3654635, max_length=100),
            preserve_default=False,
        ),
    ]
