# Generated by Django 4.0 on 2022-01-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userorder_tel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=100)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('id_picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('tel_number', models.CharField(max_length=100)),
                ('step', models.IntegerField(default=0)),
                ('active_sim', models.BooleanField(default=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.gift')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.client')),
                ('sim_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.simcardoption')),
            ],
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='sim_type',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user_gift',
        ),
        migrations.DeleteModel(
            name='SimUser',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
