# Generated by Django 4.0 on 2022-01-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_client_simorder_remove_userorder_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
